language: java
install: true
jdk:
- oraclejdk8
script:
- "./gradlew build --stacktrace"
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
    all_branches: true
notifications:
  slack:
    rooms:
    - codingnomads2019:d1aWT8GvnxhOMXgNmiIHV0eJ#java-travis
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_f467322827f3_key -iv $encrypted_f467322827f3_iv
  -in keys/mykey.enc -out keys/mykey -d

- openssl aes-256-cbc -K $encrypted_f467322827f3_key -iv $encrypted_f467322827f3_iv
  -in keys/awskey.pem.enc -out keys/awskey.pem -d
